on:
  push:
    branches:
      - main
    paths:
      - src/BH.DIS.SDK/*
env:
  BuildConfiguration: release

jobs:
  Build_Application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Test
        uses: "./.github/template/build-sdk-template"
